---

version: '3'

services:
  gcc:
    image: gcc:12
    container_name: 'gcc'
    working_dir: '/home/TechLabSatoru'
    tty: true
    volumes:
      - "./:/home/TechLabSatoru/"
  golang:
    image: golang:bullseye
    container_name: 'golang'
    working_dir: '/home/TechLabSatoru'
    tty: true
    volumes:
      - "./:/home/TechLabSatoru/"
